### ISSUE TITLE
Read Only Errors in Stdout of "jupyter lab"?

### ISSUE THREAD

**Issue by falloutphil** [guix-science/guix-science#10]
Hi,

Just installed python-jupyterlab and seems to be working  - I did notice that when creating a notebook - be it python or guix-jupyter based, that the stdout from `jupyter lab` have a bunch of read-only errors with what looks like the webserver trying to write into the gnu store.

Things seems to be working OK despite this, but was wondering if this was a known issue, or unique to my setup?  Do I have to pass in some custom config to point to writable locations?

```shell
$ guix describe
Generation 32	Oct 03 2021 17:54:26	(current)
  guix c98c9c5
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: c98c9c514261d7e870e9eb13673a3faaa46b998d
  guix-science b574aa6
    repository URL: https://github.com/guix-science/guix-science.git
    branch: master
    commit: b574aa67743cd4f138fd32efb7c116342f360625
  nonguix 3246eac
    repository URL: https://gitlab.com/nonguix/nonguix
    branch: master
    commit: 3246eac4fe6d7cab88ea21d9de902caf4aa6e522
```

```shell
guix environment --ad-hoc python-jupyterlab guix-jupyter
jupyter lab
```

```shell
[I 18:14:29.958 LabApp] Kernel started: bd86ce25-41e2-4388-9b8d-4ea7011199d5, name: guix
[W 18:14:30.192 LabApp] 500 PUT /lab/api/workspaces/lab?1633281270190 (127.0.0.1): [Errno 30] Read-only file system: '/gnu/store/9zikasyb62q8b4v3c2n6qgl55dw7hfm2-profile/etc/jupyter/lab'
[W 18:14:30.192 LabApp] [Errno 30] Read-only file system: '/gnu/store/9zikasyb62q8b4v3c2n6qgl55dw7hfm2-profile/etc/jupyter/lab'
[E 18:14:30.193 LabApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0",
      "Accept": "*/*",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/lab",
      "Content-Type": "text/plain;charset=UTF-8",
      "Authorization": "token 8564806bac3445d88d7e276cd97c6f818a9b990b7e00f8e6",
      "X-Xsrftoken": "2|dbdf2c34|4f331bd49e9b9b1b1227835e10bb26de|1634216059",
      "Origin": "http://localhost:8888",
      "Content-Length": "521",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1634216059|23:username-localhost-8888|44:MjPjYzAzZDRkYmRiPGJhMWIyYWI5Kzhj3DY5NWY1ZGI=|38e4779f2a4f67c75c79f15de5e241b0ac25f45f3e8c9e337189076bb26a4f41\"; _xsrf=2|dbdf2c34|4f331bd49e9b9b1b1227835e10bb26de|1634216059",
      "Sec-Fetch-Dest": "empty",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Site": "same-origin",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 18:14:30.193 LabApp] 500 PUT /lab/api/workspaces/lab?1634216059 (127.0.0.1) 1.300000ms referer=http://localhost:8888/lab
guix[17816]: Guix kernel started (PID 16816)
```

**Comment by PromyLOPh** [comment]
Yeah, this is a known issue, but since it didn’t cause any trouble so far, I haven’t looked into it. You can try to set the environment variable `JUPYTER_CONFIG_DIR` to a different (writable) config dir, but ultimately we’d have to figure out why it tries to write there and stop it from doing so. Hm, or maybe use `JUPYTER_CONFIG_PATH` instead in the package `python-jupyter-core`.

**Comment by falloutphil** [comment]
Thanks for the tips.  I was able to remove the errors from stdout, and other issues by making local copies of the **application** and **user settings** directories:

```shell
$ jupyter lab path
Application directory:   /gnu/store/4scp9p1fsbapv3h2pzqhj2aiv6qb8lzd-python-jupyterlab-2.2.9/share/jupyter/lab
User Settings directory: /gnu/store/fis32ai8accpwamrjmscy66g6clrz1hx-profile/etc/jupyter/lab/user-settings
Workspaces directory: /gnu/store/fis32ai8accpwamrjmscy66g6clrz1hx-profile/etc/jupyter/lab/workspaces
```

I then made local copies using `cp -RL` to copy the contents of the symbolic links in the gnu store, into local directories, and running `chmod -R +w *` over them.  (I appreciate this running roughshot over almost every Guix principle, but needs must!).

From there not only did all the stdout/err messages disappear, but I was also able to install extensions too:

```shell
export JUPYTER_CONFIG_DIR=/home/foo/jl/cfg
export JUPYTERLAB_DIR=/home/foo/jl/app
```

Then the last gotcha I had was I needed to update my ca-certificates and then set the following for `yarn` packager to function (it should probably be using nss-certs package but the below works):

```shell
export SSL_CERT_DIR=/etc/ssl/certs
```

Then I was able to do the following to get ipywidgets to install using the standard v2 instructions:

```shell
jupyter labextension install @jupyter-widgets/jupyterlab-manager --debug
```

Obviously this is not very Guixy - but it works.

Things I think will get easier with JupyterLab v3.0 as the rebuild step seems no longer required in order to install extensions.  I see there is already a branch for this but hasn't seen much action of late - is this working reasonably well?

**Comment by PromyLOPh** [comment]
Version 3 unfortunately depends on Guix’ core-updates-frozen, because a dependency requires a newer version of setuptools, which is not upgradeable, because it is bundled with the python package. (See my message here: https://issues.guix.gnu.org/46848#9 – unfortunately my push for PEP 517 has not been very fruitful so far and I don’t know what the status of core-updates-frozen is right now)

**Comment by PromyLOPh** [comment]
I upgraded JupyterLab to v3 in commit af11d1588ab10b45942ef184c4fb0d7f486c88a7.
