### ISSUE TITLE
RStudio build fails

### ISSUE THREAD

**Issue by Evolto2019** [guix-science/guix-science#17]
The build of rstudio-2021.09.2+382 in the channel failed in the "configure" phase. This also happens on the substitute server https://guix.bordeaux.inria.fr/. The last successful build was on 15 July.
Relevant logs can be viewed at https://guix.bordeaux.inria.fr/search?query=rstudio-2021.09.2%20382&border-low-id=15000

**Comment by PromyLOPh** [comment]
This looks like an issue caused by the switch to Qt6 on Guix proper. I’m building a local fix now and will push if it succeeds.
