### ISSUE TITLE
python-tornado conflict in python-jupyterhub

### ISSUE THREAD

**Issue by danyel2014** [guix-science/guix-science#18]
Hey guys, 

I'm trying to install `python-jupyterhub` - fresh profile, but I get the next error:

` $ guix package -p jupyterhub-guix -i python-jupyterhub
The following package will be installed:
   python-jupyterhub 1.4.1
guix package: error: profile contains conflicting entries for python-tornado
guix package: error:   first entry: python-tornado@5.1.1 /gnu/store/i23vy8nixgk2dfchj444p1x1sxjh9pxf-python-tornado-5.1.1
guix package: error:    ... propagated from python-jupyterhub@1.4.1
guix package: error:   second entry: python-tornado@6.1 /gnu/store/ihlxpxpxxqzmq5alpd4f5kbwn3idpf8a-python-tornado-6.1
guix package: error:    ... propagated from python-notebook@6.4.10
guix package: error:    ... propagated from python-jupyterhub@1.4.1
hint: You cannot have two different versions or variants of python-jupyterhub in the same profile.`

The output of the `guix describe` is below:
` $ guix describe
Generation 6	Aug 29 2022 20:49:21	(current)
  guix 9529384
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: 9529384c92e6427e7d277ffaa391405ef6ab22f3
  guix-science 948c6a3
    repository URL: https://github.com/guix-science/guix-science.git
    branch: master
    commit: 948c6a3273e84c2ffc929576a5483ba34cf24074`

Could you please check and fix this error?
Thank you
Dan

**Comment by PromyLOPh** [comment]
Thanks for the report, should be fixed now!

**Comment by danyel2014** [comment]
Hi @PromyLOPh ,

I've tested  `python-jupyterhub` and it works, but it seems that `python-jupyterhub-ldapauthenticator` is affected by the same issue. 

Could you please check?

Thanks
Dan

**Comment by PromyLOPh** [comment]
Also fixed.
