### ISSUE TITLE
python-jupyterhub-ldapauthenticator - python-tornado conflict

### ISSUE THREAD

**Issue by danyel2014** [guix-science/guix-science#19]
Hi again, 

the `python-jupyterhub-ldapauthenticator`  is affected by the same issue #18.

Could you please fix this also?

Thanks

Dan

**Comment by rekado** [comment]
Does commit dad7a6f9c9bc808c118a27b5a97eff3a81767659 not address this?

**Comment by danyel2014** [comment]
both the issue and the commit are 7 hours old (at this moment), so I cannot say if the commit has been done a short time before or after opening the issue. Anyway,  now the package can be installed without errors.
Thanks

**Comment by rekado** [comment]
issue: 12:46pm, commit: 12:22pm
close enough to miss it :)
