### ISSUE TITLE
Substitute server status?

### ISSUE THREAD

**Issue by raingloom** [guix-science/guix-science#22]
I authorized the key and explicitly passed the substitute server on the command line, but RStudio is still being built from source.

Is there a public Cuirass frontend where build logs could be checked, so users could have some sense of whether the build failed or if it's pending?

**Comment by raingloom** [comment]
Also. https://sfconservancy.org/GiveUpGitHub/
:)

**Comment by PromyLOPh** [comment]
I’m rebooting the server. `guix-publish` has been crashing alot lately unfortunately, but I don’t know why. There’s also INRIA’s substitute server if ours does not work, see https://hpc.guix.info/channels/ and https://guix.bordeaux.inria.fr/jobset/guix-science

Moving a guix channel is very painful. I’m not going to do that unless absolutely necessary.
