### ISSUE TITLE
CRAN packages should be in Guix proper

### ISSUE THREAD

**Issue by rekado** [guix-science/guix-science#8]
There are some CRAN packages, which really shouldn't be in guix-science but in Guix proper instead.
The following packages don't seem to have any dependency on packages that cannot be upstreamed:

- r-rmisc
- r-glinternet
- r-norm
- r-naniar

We should move those packages to Guix and prevent fine CRAN packages from being added to guix-science needlessly.

**Comment by PromyLOPh** [comment]
I’m not sure about r-norm’s license, but I’ll assume good faith (it was released in 1999) and add it as `(non-copyleft "file://LICENSE")`.

**Comment by PromyLOPh** [comment]
Pushed upstream as https://github.com/guix-mirror/guix/commit/f6802a924711858d82939dde39caceacf57c96ad and following.
